<a href="https://colab.research.google.com/github/ililillilili1/test2/blob/DA/page4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#넘파이
파이썬에서 배열을 사용하기 위한 표준 패키지

리스트로 배열 생성

In [ ]:
#1차원배열(list)로 numpy 배열 생성

import numpy as np
arr=np.array([1,2,3,4,5]) #넘파아의 array함수에 리스트 추가하기
print(arr)

[1 2 3 4 5]


In [ ]:
#2차원배열(list)로 numpy 배열 생성
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3차원배열(list)로 numpy 배열 생성
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]
              , [[1,2,3], [4,5,6], [7,8,9]]
              , [[1,2,3], [4,5,6], [7,8,9]]
              ])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


배열 생성 및 초기화

#함수
- zeros(형태, dtype=타입, order='C') : 주어진 형태와 타입을 갖는 0으로 채워진 배열을 반환
- ones(형태, dtype=타입, order'C') : 주어진 형태와 타입을 갖는 1로 채워진 배열을 반환
- np.full(형태, fill_value, dtype=None, order='C') : 지정한 shape 배열 생성, 모든 요소를 fill_value  로 채움
- np.eye(N,M=None, k=0, dtype=<class 'float'>) : (N,N) 형태의 단위행렬 생성

In [ ]:
a=np.zeros(10)
print(a)
#[0,0,0,0,0,0,0,0,0,0]

b=np.zeros((3,3))
print(b)
#[[0,0,0]
  [0,0,0]
  [0,0,0]]

c=np.ones(10)
print(c)
#[1,1,1,1,1,1,1,1,1,1]



생성한 값으로 배열 생성
: 주어진 조건으로 데이터를 생성한 후, 배열을 만듦

#np.arrange()
import numpy as np
numpy.arange([start,]stop[,step,],dtype=None)

start 부터 stop 미만까지 step 간격으로 데이터를 생성한 후 배열을 생성

In [ ]:
import numpy as np
a=np.arange(1,21)
print(a)
#[ 1 2 3 4 5 .... 20]

#np.linspace()

numpy.linspace(start,stop,num)
start 부터 stop 까지 범위에서 num개를 균일한 간격으로 데이터를 생성하고 배열을 만드는 함수
요소 개수를 기준으로 균등 간격의 배열 생성

In [ ]:
a=np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


#np.logspace()
numpy.logspace(start,stop,num)
로그 스케일로 지정된 범위에서 ~ linspace 와 같음

In [ ]:
a=np.logspace(np.log10(10),np.log10(100), 5)
print(a)

b=np.logspace(1,2,5)
print(b)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


#난수 기반 배열 생성

<함수>
- seed
- shuffle : 리스트나 배열의 순서 섞음
- random : 랜덤한 수의 배열 생성
- randint : 일정 구간의 랜덤 정수 배열 생성
- rand : 균등분포에서 표본 추출
- randn : 표준편차가 1, 평균값 0인 정규분포의 표본 추출
- normal : 정규분포를 고려한 랜덤한 수의 배열 생성



In [ ]:
#random

a=np.random.random()
print(a)
a=np.random.random((4,4))
print(a)

# 왜 0.xxxx로 생성되는걸까


#randint
a=np.random.randint(1,10)
print(a)
a=np.random.randint(1,10,(4,4))
print(a)

#rand
#[1,0]의 균등분포 형상으로 표본 추출
a=np.random.rand(3,3)
print(a)

#randn()
#표준정규분포에서 표본 추출
a=np.random.randn(3,3)
print(a)

0.5342069478020676
[[0.10526127 0.77524595 0.56924076 0.59248648]
 [0.85108453 0.6042101  0.00815439 0.83589814]
 [0.70537887 0.03958462 0.56779908 0.10552847]
 [0.88190507 0.92886482 0.72303612 0.83891959]]
7
[[7 9 9 8]
 [8 1 4 7]
 [9 1 9 6]
 [9 1 8 7]]
[[0.90948145 0.32747529 0.79106127]
 [0.43267034 0.60249347 0.41906393]
 [0.86015709 0.34464875 0.44155278]]
[[ 0.21894548 -1.3168515   0.23298474]
 [-0.56925052 -0.2802524  -0.24744991]
 [ 0.6339987  -2.85812631 -0.61543259]]


#배열 변환

- 전치
- 배열 형태 변경
- 배열 요소 추가 및 삭제
- 배열 결합
- 배열 분리

In [ ]:
#전치: 행렬의 인덱스가 바뀌는 변환

import numpy as np

a=np.random.randint(1,10,(3,3))
print(a)
print(a.T)


[[5 8 5]
 [1 2 8]
 [9 4 2]]
[[5 1 9]
 [8 2 4]
 [5 8 2]]


In [ ]:
#배열 형태 변경

import numpy as np

#ravel : 배열을 1차원 배열로 변환
a=np.array([[1,2,3], [4,5,6]])
a.ravel() #?
print(a)
b=a.ravel()
b[0] = 10
print(b) #[10,2,3,4,5,6]
print(a)

print('\n')

#reshape : np.ndarray 의 shape 변경
x=np.arange(20)
y=x.reshape(4,5)
print(y)
x[0] = 10
print(x)
print(y)

print('\n')

#다차원 list 데이터를 reshape 하기

list_data=[1,2,3,4,5,6]
data=np.array(list_data)
type(data)
print(data.reshape(3,2))
print(list_data)



[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[[1 2]
 [3 4]
 [5 6]]
[1, 2, 3, 4, 5, 6]


In [ ]:
#배열 요소 추가 및 삭제

#resize 함수
x=np.arange(20)
y=np.resize(x,(5,4))
y
#요소 수가 더 많은 경우
z=np.resize(x,(5,6)) #이렇게 요소 수를 조절해도 다른 배열에는 영향 없음
z

#append 함수 : 값 추가
a = np.arange(3)
b = np.append(a,3)
print(b)

#배열 추가
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9]])
c=np.append(a,b)
print(c) #축을 지정하지 않을 경우 1차원 배열로 변환되어 생성
d=np.append(a,b,axis=0)
print(d) #축을 지정할 경우 2차원 배열로 출력

print("\n")

#insert 함수 : 주어진 축에 대해 주어진 인덱스 앞에 값을 삽입함
a=np.array([[1,1],[2,2],[3,3]])
d=np.insert(a,1,5,axis=1)
c=np.insert(a,1,5,axis=0)
b=np.insert(a,1,5) #축 지정 X 이므로 1차원 배열로 반환
print(a)
print(b) #1차원
print(c) #배열의 첫번쨰 축을 따라 5 삽입
print(d) #배열의 두번째 축을 따라 5 삽입

print("\n")

#delete 함수 : 인덱스 배열의 요소 또는 서브 배열 제거
a=np.arange(12).reshape(3,4)
print(a)
print(np.delete(a,5))
print(np.delete(a,1,axis=0))
print(np.delete(a,1,axis=1))


[0 1 2 3]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 1]
 [2 2]
 [3 3]]
[1 5 1 2 2 3 3]
[[1 1]
 [5 5]
 [2 2]
 [3 3]]
[[1 5 1]
 [2 5 2]
 [3 5 3]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [ ]:
#배열 결합

#concatenate 함수 : 배열의 시퀀스를 지정한 축을 따라 연결한다
a1=np.array([[1,2,3]])
a2=np.array([[4,5,6]])
arr=np.concatenate((a1,a2))
arr1=np.concatenate((a1,a2),axis=0) #첫번쨰줄(세로) 를 따라 연결
arr2=np.concatenate((a1,a2),axis=1) #두번째줄(가로) 를 따라 연결
print(arr)
print(arr1)
print(arr2)

print("\n")
#vstack 함수 : 배열의 시퀀스를 지정한 축을 따라 연결한다 (세로(axis=0)연결만 가능)
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.vstack((a1,a2))
print("\n")

#hstack함수 : 배열의 시퀀스를 지정한 축을 따라 연결한다 (가로(axis=1)연결만 가능)
a1=np.array([1,2,3])
a2=np.array([4,5,6])
np.hstack((a1,a2))
print("\n")


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]








In [ ]:
#배열 분리

#hsplit함수 : 배열을 수평 방향으로 분할
#vsplit함수 : 배열을 수직 방향으로 분할

a=np.arange(16).reshape(4,4)
a_hsplit=np.hsplit(a,2)
a_vsplit=np.vsplit(a,2)
print(a)
print(a_hsplit)
print(a_vsplit)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


#연습문제

In [ ]:
import numpy as np

#1
arr=np.arange(1,11)
print(arr)
print('ndim', arr.ndim)
print('(%d,)' %arr[9])
print('int%d' %(arr[7]*arr[7]))
print('size:%d' %(arr[9]))

[ 1  2  3  4  5  6  7  8  9 10]
ndim 1
(10,)
int64
size:10


In [ ]:
#2
import numpy as np

#2_1
arr=np.arange(10,51)
arr_reverse=np.flip(arr)
print(arr_reverse)
print('\n')

#2_2
arr=np.random.random((10,10))
print(arr.min(),end=' ')
print(arr.max())
print('\n')

#2_3
arr=np.arange(9).reshape(3,3)
print(arr)
print('\n')

#2_4
arr=np.arange(1,25).reshape(4,6)
print(arr)
print('\n')

#2_5
arr2=np.delete(arr,0,axis=1)
arr2=np.delete(arr2,4,axis=1)
arr2=np.delete(arr2,0,axis=0)
arr2=np.delete(arr2,2,axis=0)
print(arr2)
print('\n')

#2_6
arr1=np.delete(arr,0,axis=0)
arr1=np.delete(arr1,0,axis=0)
arr1=np.flip(arr1,axis=1)
print(arr1)
print('\n')

#2_7
print(arr[arr%2==0])

#2_8
print(arr[(arr>=10)&(arr<=20)])


[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


0.030346993097837838 0.9828927454714652


[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[[ 8  9 10 11]
 [14 15 16 17]]


[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


[ 2  4  6  8 10 12 14 16 18 20 22 24]
[10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#3
import numpy as np
arr=np.arange(1,21)
print('마지막 원소:', arr[19])
print('모든 원소의 합:', np.sum(arr))
print('모든 원소의 평균:', np.sum(arr)/len(arr))

마지막 원소: 20
모든 원소의 합: 210
모든 원소의 평균: 10.5


In [ ]:
#4
import numpy as np
salary = [200,100,150,180,220,250]
new_salary=np.array(salary, dtype='float64')*1.5
print('인상된 금액: ', new_salary)
avg_salary=np.sum(new_salary)/len(new_salary)
print('평균 금액: ', avg_salary)
result=np.array(new_salary>avg_salary)
print('평균이상인 원소: ', new_salary[result])
print('평균이상인 원소의 개수: ', np.sum(result)) #?

인상된 금액:  [300. 150. 225. 270. 330. 375.]
평균 금액:  275.0
평균이상인 원소:  [300. 330. 375.]
평균이상인 원소의 개수:  3
